### ISSUE TITLE
"Check box" addon annoyacne

### ISSUE THREAD

**Issue by garry-ut99** [tablacus/TablacusExplorer#806]
When I read about this add-on, I found it interesting, I installed it, and tried it, it works, but then I disabled it because of the following annoyance:

everytime a mouse cursor hovers over an item, an unselected check box appears automatically in a front of the item, even if an user is not interested of selecting anything, even when he is just doing other actions which are unrelated to selecting items, for example, even when an user:
   -  wants only to wait for the tooltip to appear to see some info about the item
   -  wants to right-click an item to use context menu commands 
   -  is just simply moving the mouse cursor across the window to reach a button, a tab or menu 

The point is that check boxes keep appearing and disappearing multiple times, every time a mouse cursor moves, which is a distracting annoyance. 

The solution to fix this annoyance is simple: check boxes should not appear until at least 1 file is selected, then and only then check boxes should begin to appear when hovering over items.

**Comment by ccfs** [comment]
The appearing and disappearing of checkboxes is controlled by a Windows component used by TE. Therefore your suggestion can hardly be implemented.

An alternative way is to keep the checkboxes (ticked or not) showing by opting for "XP style".

**Comment by garry-ut99** [comment]
I already tried XP style before reporting the issue, but it doesn't work as intented, as there seemed to be a some glitch, which seems to be related to a fact that I use Win 7 SP1 + small icon view and manual says: "_It does not work in small icons view on Windows 7_" (not to mention I don't like to have all checkboxes visible on screen either)

![Image](https://github.com/user-attachments/assets/9e53e562-b293-4f2b-baed-66b27a13cbd6)

**Comment by garry-ut99** [comment]
Another issue:  Since it’s impossible to keep clicking perfectly in the center of a checkbox every time, it’s normal for the cursor to hit the edge of a check box once every few times (actually it's a bit outside the check box), and when that happens, all the previous check boxes are cleared / gone, and the user needs to start from scratch. That happens often enough to make the whole "check box" feature annoying as hell and therefore almost unusable:

![Image](https://github.com/user-attachments/assets/55a3237e-ef1a-40a7-9f8d-dcecb8076726)


The possible solutions:
- to make the area around check boxes be standalone and not a part of the file / folder name area, since then clicks outside the check boxes could be just either registered as valid clicks (the check box would be marked) or just ignored. That would also fix the issue from the first comment.
- or to make check boxes bigger so that the empty space between them is eliminated or reduced greatly, which reduces the misclicks, but the side effect would be that too big check boxes would not be visually pleasant
- or to make clicking outside a check box not deselect the previous marked check boxes, to clear all the previously marked checkboxes an user would need to click empty area (background)

**Comment by ccfs** [comment]
Tick both "All" and "Background" check boxes of the add-on options. Then clicking outside a check box will not deselect anything. To deselect all check boxes, double-click empty area.

**Comment by garry-ut99** [comment]
It works, those settings weren't described at all anywhere - neither on the add-ons website nor in the add-on options, therefore I had no idea what they are supposed to do.

But there is a some glitch / side-effect after enabling "Check box" add-on (regardless of whether "All" and "Background" are ticked or not): 
- after enabling the add-on - items icons gets bigger 
- after refreshing (F5) or _Context Menu ==> Refresh_, the icons gets back to a normal size
- but then it keeps happening again over and over everytime the folder is re-entered (for example: back and forward, or close and reopen the tab, or duplicate the tab)

![Image](https://github.com/user-attachments/assets/b571f40f-1ba6-402c-bcb7-2d7a4dd569c4)

**Comment by ccfs** [comment]
(a) See TE add-on manual [PDF](https://github.com/ccfs/TablacusExplorer/issues/1).

(b) Regarding the icon size issue:

1. Enable "Copy folder settings" add-on

<img width="662" height="372" alt="Image" src="https://github.com/user-attachments/assets/d29a75a3-51f4-41e1-bce9-80a2cba4ef08" />

2. Right-click file list background (when the icon is bigger), choose "Copy folder settings", paste the text in your reply.

<img width="748" height="439" alt="Image" src="https://github.com/user-attachments/assets/027039fb-8c8a-44f9-8858-82c544e01228" />

3. Refresh the file list.

4. Right-click file list background (when the icon is normal size), choose "Copy folder settings", paste the text in your reply.

5. Choose Help > About TE, click the Copy button, paste the  the text in your reply.

**Comment by garry-ut99** [comment]
> ccfs: (a) See TE add-on manual [PDF](https://github.com/ccfs/TablacusExplorer/issues/1).

Right, I completely forgot about the PDF manual.
(_forgetting is beyond human control, it just happens to everyone from time to time_)

<br>

> ccfs: (b) Regarding the icon size issue:

it's the same in the both cases:
```
FV.SetViewMode(3,16);
FV.Columns='"System.ItemNameDisplay" 340 "System.DateModified" 150 "System.ItemTypeText" 150 "System.Size" 100';
FV.GroupBy='System.Null';
FV.SortColumn='System.ItemNameDisplay';
```

<br>

> ccfs:  Choose Help > About TE, click the Copy button, paste the the text in your reply.

I don't like being finger-printed, therefore I wll paste partial info (perhaps will provide more if required):
`TE64 25.6.8 Microsoft Windows 7 Professional  64-bit (6.1.7601) IE/11 JS/11.0.17840 pl_pl 120` + 42 addons (most of them same like previously: `https://github.com/tablacus/TablacusExplorer/issues/849#issuecomment-2994332437`)

However, I've managed to track down the addon that triggers the issue: `Fast list mode 1.04`. The issue is gone after disabling the addon (but I need that addon).

**Comment by ccfs** [comment]
The problem is not caused by "Fast list mode" add-on. It is caused by "Check box" add-on while the display size is 125% as set in Windows Control Panel. It happens when the view mode is Details, List and Small Icon.

That icon sizing is probably not done in JScript. Therefore I cannot solve the problem.

**Comment by garry-ut99** [comment]
> ccfs: The problem is not caused by "Fast list mode" add-on

I didn't said it's "caused", I only said it's triggered, they are not same words / synonyms: triggered means only that an issue occurs / is present when an addon X is enabled, which doesn't necessarily mean that the add-on X is causing the issue. 

(_it's unclear whether your intention is to contradict (wrongly) what I wrote, or whether to only provide an information, and that's how it sounds (wrong contradiction/denial due to the mistaken assumption that different words have the same meaning), therefore someone might interpret it wrongly that way, so I've just made it clear_).

<br>

> ccfs: That icon sizing is probably not done in JScript. Therefore I cannot solve the problem.

Well, I've noticed that the issue is not only about icon sizing glitch (too large), but also the whole feature " Tick both "All" and "Background" " stops working (misclicks clear the previous checked boxes) until the icons glich is fixed (F5 referesh).

**Comment by ccfs** [comment]
I have found that the problem actually happens in any view mode upon view mode change or navigation. Please install the [patch](https://github.com/tablacus/TablacusExplorer/issues/692) to get over it.

**Comment by garry-ut99** [comment]
Yes, it's fixed now (the both issues).

**Comment by ccfs** [comment]
The patched version of the add-on has been updated:
- some unreported problems are fixed
- the options are now stated in understandable phrases

**Comment by garry-ut99** [comment]
Looks good, but there is a side-effect now: the same problem is back again: https://github.com/tablacus/TablacusExplorer/issues/806#issuecomment-4083584512.

Given:
- a1) misclicking on the 2nd (and more) check box never deselects the previous checked boxes
- a2) misclicking on the 2nd (and more) check box always deselects the previous checked boxes)
- b1) clicking on the 2nd (and more) item name never deselects the previous item name
- b2) clicking on the 2nd (and more) item name always deselects the previous item name

Previously I could have: [a1 + b2] at the same time
Now I can have only: either: [a1 + b1] or [a2 + b2]

They are good options, so they should stay but the previous option [a1 + b2] was resonable as well because when misclicking on the 2nd (and more) check box the user still wants / expects to add another check box to the pile (without clearing the previous), as that's the purpose of check boxes.

If user ever wanted to deselect the previous item when clicking another item (for example the user is just checking single item properties or doing some commands from the item's context menu), he will just simply click the item name (iterate over item names one by one) instead of check boxes, and he will expect the previous selected item name to be always deselected. Therefore I'm for adding the [a1 + b2] combination to the pile of existing combinations, unless that causes some side effects of which I'm unaware.

**Comment by ccfs** [comment]
This version should still handle selection in the same way as the previous version, if you have not changed any options.

Please show me a screen capture of your "Check box" add-on options page, and a gif showing the problem you get with the CURRENT version.

**Comment by garry-ut99** [comment]
<img width="1018" height="338" alt="Image" src="https://github.com/user-attachments/assets/1a699749-bfea-40dc-946a-60ead2637016" />

<br>
<br>

![Image](https://github.com/user-attachments/assets/83b56d17-043e-4ac3-aac1-2d9eac8838b7)

**Comment by ccfs** [comment]
The add-on has been updated so that if you click the blank space around a check box, it is treated as if you had hit the check box.

**Comment by garry-ut99** [comment]
The issue is fixed now.
